import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

/**
 * Service to handle GitHub operations using stored user tokens
 */
export async function createFixPR(userId: string, repoFullName: string, violation: any) {
  try {
    // 1. Fetch the GitHub integration for the user
    const { data: integration, error } = await supabase
      .from('integrations')
      .select('*')
      .eq('user_id', userId)
      .eq('type', 'github')
      .single();

    if (error || !integration) {
      throw new Error("GitHub integration not found for this user.");
    }

    const token = integration.config.access_token;
    const headers = {
      'Authorization': `token ${token}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json'
    };

    // 2. Get the default branch and latest commit
    const repoRes = await fetch(`https://api.github.com/repos/${repoFullName}`, { headers });
    const repoData: any = await repoRes.json();
    if (!repoRes.ok) throw new Error(`GitHub Repo API Error: ${repoData.message}`);
    
    const defaultBranch = repoData.default_branch;

    const refRes = await fetch(`https://api.github.com/repos/${repoFullName}/git/ref/heads/${defaultBranch}`, { headers });
    const refData: any = await refRes.json();
    const latestSha = refData.object.sha;

    // 3. Create a new branch for the fix
    const branchName = `luminary-remediation-${violation.id.toLowerCase()}-${Math.floor(Math.random() * 1000)}`;
    const branchRes = await fetch(`https://api.github.com/repos/${repoFullName}/git/refs`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        ref: `refs/heads/${branchName}`,
        sha: latestSha
      })
    });

    if (!branchRes.ok) {
        const err = await branchRes.json();
        throw new Error(`Failed to create branch: ${err.message}`);
    }

    // 4. Create a Pull Request with the AI remediation details
    // Note: For a real PR, we would need to know the file path to edit.
    // In Phase 12, we create a specialized 'remediation.md' file to demonstrate the capability.
    
    const prContent = `
# Luminary Accessibility Remediation
## Violation: ${violation.help} (${violation.id})

**Description:** ${violation.description}
**Impact:** ${violation.impact.toUpperCase()}

### Proposed Code Fix:
\`\`\`html
${violation.ai_fix || "Check report for details"}
\`\`\`

---
*This PR was automatically generated by Luminary AI.*
    `;

    // Create the file in the new branch
    await fetch(`https://api.github.com/repos/${repoFullName}/contents/LUMINARY_FIX.md`, {
      method: 'PUT',
      headers,
      body: JSON.stringify({
        message: `[Luminary] Accessibility fix for ${violation.id}`,
        content: Buffer.from(prContent).toString('base64'),
        branch: branchName
      })
    });

    // Finalize the PR
    const prRes = await fetch(`https://api.github.com/repos/${repoFullName}/pulls`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        title: `[Luminary] Accessibility Remediation: ${violation.help}`,
        head: branchName,
        base: defaultBranch,
        body: `Luminary has identified a ${violation.impact} accessibility violation and generated a proposed fix. \n\nSee the attached LUMINARY_FIX.md for details.`
      })
    });

    const prData = await prRes.json();
    return { success: true, url: prData.html_url };

  } catch (error: any) {
    console.error("GitHub PR Service Error:", error);
    return { success: false, error: error.message };
  }
}
